[2024-12-04T02:06:42.815+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction scheduled__2024-12-03T00:00:00+00:00 [queued]>
[2024-12-04T02:06:42.845+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction scheduled__2024-12-03T00:00:00+00:00 [queued]>
[2024-12-04T02:06:42.847+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-12-04T02:06:42.901+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): reddit_extraction> on 2024-12-03 00:00:00+00:00
[2024-12-04T02:06:42.948+0000] {standard_task_runner.py:60} INFO - Started process 636 to run task
[2024-12-04T02:06:42.959+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_reddit_pipeline', 'reddit_extraction', 'scheduled__2024-12-03T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmpugpyl7oc']
[2024-12-04T02:06:42.968+0000] {standard_task_runner.py:88} INFO - Job 16: Subtask reddit_extraction
[2024-12-04T02:06:43.231+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_reddit_pipeline.reddit_extraction scheduled__2024-12-03T00:00:00+00:00 [running]> on host 67b23099d8b1
[2024-12-04T02:06:43.500+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='viswa' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='reddit_extraction' AIRFLOW_CTX_EXECUTION_DATE='2024-12-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-03T00:00:00+00:00'
[2024-12-04T02:06:45.243+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 9, in reddit_pipeline
    posts=extract_posts(instance,subreddit,time_filter,limit)
  File "/opt/airflow/etls/reddit_etl.py", line 42, in extract_posts
    'User-Agent': user_agent,
NameError: name 'user_agent' is not defined
[2024-12-04T02:06:45.307+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=reddit_extraction, execution_date=20241203T000000, start_date=20241204T020642, end_date=20241204T020645
[2024-12-04T02:06:45.360+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 16 for task reddit_extraction (name 'user_agent' is not defined; 636)
[2024-12-04T02:06:45.394+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-12-04T02:06:45.486+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
