[2024-12-04T02:06:42.815+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-12-04T02:06:19.422298+00:00 [queued]>
[2024-12-04T02:06:42.854+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-12-04T02:06:19.422298+00:00 [queued]>
[2024-12-04T02:06:42.856+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-12-04T02:06:42.914+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): reddit_extraction> on 2024-12-04 02:06:19.422298+00:00
[2024-12-04T02:06:42.957+0000] {standard_task_runner.py:60} INFO - Started process 637 to run task
[2024-12-04T02:06:42.974+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_reddit_pipeline', 'reddit_extraction', 'manual__2024-12-04T02:06:19.422298+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmp7y_kspgn']
[2024-12-04T02:06:42.984+0000] {standard_task_runner.py:88} INFO - Job 15: Subtask reddit_extraction
[2024-12-04T02:06:43.227+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-12-04T02:06:19.422298+00:00 [running]> on host 67b23099d8b1
[2024-12-04T02:06:43.500+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='viswa' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='reddit_extraction' AIRFLOW_CTX_EXECUTION_DATE='2024-12-04T02:06:19.422298+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-04T02:06:19.422298+00:00'
[2024-12-04T02:06:45.266+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 9, in reddit_pipeline
    posts=extract_posts(instance,subreddit,time_filter,limit)
  File "/opt/airflow/etls/reddit_etl.py", line 42, in extract_posts
    'User-Agent': user_agent,
NameError: name 'user_agent' is not defined
[2024-12-04T02:06:45.314+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=reddit_extraction, execution_date=20241204T020619, start_date=20241204T020642, end_date=20241204T020645
[2024-12-04T02:06:45.353+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 15 for task reddit_extraction (name 'user_agent' is not defined; 637)
[2024-12-04T02:06:45.397+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-12-04T02:06:45.475+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
